server:
  port: 8999
ldap:
  base: dc=siemens,dc=com
  host: 10.192.30.193
  port: 389
  url: ldap://${ldap.host}:${ldap.port}
  userDn: cn=manager,dc=siemens,dc=com
  password: dpp123##
  referral: follow
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: pgsql
    url: jdbc:postgresql://10.193.9.103:5432/pgsql
    password: Dpp-pgsql123##
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
